services:

  mysql:
    image: mysql
    restart: always
    ports:
      - 127.0.0.1:3306:3306
    volumes:
      - ./database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: toor

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 127.0.0.1:8090:80
    environment:
      - PMA_ARBITRARY=1